# Material Design
This lecture discusses [Material design](https://material.io/guidelines/material-design/introduction.html): the _design language_ created by Google to support mobile user interfaces. The design language focuses on mobile designs (e.g., for Android), but can also be used across platforms (e.g., on the web through [css frameworks]()).

<p class="alert alert-info">This lecture references code found at <https://github.com/info448-s17/lecture14-material>.</p>

## The Material Design Language `r#[15-20min]`
See video: https://www.youtube.com/watch?v=YaG_ljfzeUw (via https://developer.android.com/design/material/index.html)

Summary:
- based on "materials": in particular, idea of surfaces (pieces of paper) floating in space
  - uniform thickness (1dp), but at different elevations (depths)
    - Each element ahs default resting elevation, but can change in response to user input
      - use shadows to indicate current elevation
      - Helps to indicate _perspective_
    - don't occupy same space!
  - can change shape, size, position (along plane); but doesn't fold; can split and rejoin
  - motion/interaction: inputs stay within material, material doesn't pass through materials
    - can move on any axis, but z-axis (up and down) is for user interaction!
- aesthetic choices (color, fonts, etc)
- motion within a single environment: content moves and reorganizes in response to user input
- **Object Hierarchy**; group visual components into hierarchy (parent-child), with some rules:
  - children move with parent (e.g., scrolling); includes transformations (scales, elevation changes, etc)
  - children have minimal elevation diff from parents, and other objects don't get inserted inbetween
  - Note: this may not correspond to an actual View hierarchy!

Links:
- https://material.io/guidelines/material-design/introduction.html#introduction-principles
- **https://material.io/guidelines/material-design/material-properties.html**
- **https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-elevation-android**

Note: talked about using material theme/styling in lab!
- Have included a few theme tricks (can go over)

## Design Support Library
Include it:

```
compile 'com.android.support:design:25.3.1'
```

### Fabs
- basically a "styled" button... but also will have extra benefits later!
  - e.g., snackbar with coordinatorLayout

### Cards
```
compile 'com.android.support:cardview-v7:25.3.1'
```

different library, but still support
- include an image in the card?


### Navigation Drawers
- add extra wrapping


### CoordinationLayout
- create a scrolling activity, look at that!
  - Intent our way to it
- can build a coodinator layout into Main and see how it works (sorta...) :)

http://saulmm.github.io/mastering-coordinator
https://lab.getbase.com/introduction-to-coordinator-layout-on-android/


## Material Animations

### Transitions
```xml
<!-- in style: enable window content transitions -->
<item name="android:windowActivityTransitions">true</item>
```

Make buttons map:
- add `android:transitionName` to each
- wrap scrollview `anchor` in FrameLayout

```java
ActivityOptions options = ActivityOptions.makeSceneTransitionAnimation(MainActivity.this, fab, "fab"); //for single item
// start the new activity
startActivity(new Intent(MainActivity.this, ScrollingActivity.class), options.toBundle());
```

https://material.io/guidelines/motion/material-motion.html //design language!


---
---
---


## Implementing Material [30-40min]
//only available in Android 5.0 (API 21) or higher! Can get some pieces in lower APIs with backwards compatibility, but need to do some work https://developer.android.com/training/material/compatibility.html

**Material Theme** //cover in lab previously << recall from lab!

**Lists and Cards** [20min?]
- implementing RecyclerView??
- Providing a card view ((can do without the Recycler?))
>> should include this as well...

**Assigning Elevation** [5-10min]
- e.g., demo for buttons! (elevation + translation)
- how to change shape??
  - can move from rectangle to circle automatically? Check the `Outline` class...

**Animations** [30min? or skip?? (come back to later)]
- include some defaults (demo??)
- Do these need to be specified?
  - reveal
- transitions (e.g., between Fragments) are neat!
-
does Property Animation go here?... I think so (at least interpolation as a piece)... or do that set of transitions later (lab?)

**Drawables** ??
- meh


## Design Support Library [30-40mins]
- Floating Action Button [5min] << could be something to modify/demo with!
- Navigation Drawer (via support library; vs. v4 library? _what's the difference?_)
  - Not too bad: filling in XML (20min?)

- CoordinatorLayout omg wtf (go hog wild!!)
  - will need pictures/icons for... something?
